### ISSUE TITLE
Bad / incorrect example: "Only Block Incoming Traffic"

### ISSUE THREAD

**Issue by otheus** [trimstray/iptables-essentials#2]
The title "Only Block Incoming Traffic" and provided code make no sense together. The code clearly ACCEPTS all incoming traffic.  All outbound traffic is allowed as well. 

https://github.com/trimstray/iptables-essentials#only-block-incoming-traffic

I'd offer an alternative, but it's not clear what the author had intended.

**Comment by trimstray** [comment]
Thanks a lot, yes you're right. Do you have any ideas what to improve in this repository? Could you add a pull request for this issue? :)
